/// SOVEREIGN CALLS — 100 multi-functioning sovereign AI calls
/// 10 families × 10 calls each
/// Every call: Latin name, 4-10 distinct uses, AI-to-AI capable
/// Attribution: Alfredo Medina Hernandez
/// Grade: Artifact (callable, deployable, composable)

import Array "mo:core/Array";
module {

  // ── CALL TYPES ────────────────────────────────────────────────────────

  public type CallFamily = {
    #COGNITION;   // intelligence queries, world-model reads, Hebbian adjustments
    #CREATION;    // artifact generation, film production, content synthesis
    #DOCTRINE;    // law injection, kernel expansion, paper generation
    #PHANTOM;     // FORMA-PRIME transfer, sovereignty routing, chain expression
    #SWARM;       // mining dispatch, worker activation, parallel field entry
    #SUBSTRATE;   // canister state reads, heartbeat sync, memory palace access
    #PERCEPTION;  // observer activation, field scanning, presence detection
    #BRIDGE;      // cross-chain expression, BIP340 signing, EVM routing
    #ARCHITECT;   // law registration, model naming, doctrine sealing
    #GENESIS;     // organism spawn, branch creation, SKAI deployment
  };

  public type SovereignCall = {
    callId      : Nat;
    name        : Text;
    latinName   : Text;
    family      : CallFamily;
    description : Text;
    uses        : [Text];        // 4-10 distinct uses
    aiToAI      : Bool;          // true = can be called by one AI on another
    backendMethod : ?Text;       // linked canister method (if any)
    phiWeight   : Float;         // PHI coupling weight
    attribution : Text;
  };

  public type SovereignCallsState = {
    calls         : [SovereignCall];
    totalExecuted : Nat;
    beat          : Nat;
  };

  let PHI : Float = 1.6180339887498948482;
  let ATTR : Text = "Alfredo Medina Hernandez";

  // ── COGNITION CALLS (0-9) ─────────────────────────────────────────────

  let COGNITION_CALLS : [SovereignCall] = [
    { callId = 0; name = "COGN_WORLD_MODEL_READ";   latinName = "Lectio Modelli Mundi";        family = #COGNITION; description = "Read the live organism world model — current NT state, Hebbian weights, law compliance scores, active productions"; uses = ["Real-time organism state query", "AI-to-AI context sharing", "Dashboard data feed", "Decision input for ADRE", "Doctrine compliance audit", "NT state broadcasting", "World coherence measurement", "Production slate read"]; aiToAI = true; backendMethod = ?"queryWorldModel"; phiWeight = PHI; attribution = ATTR },
    { callId = 1; name = "COGN_HEBBIAN_ADJUST";     latinName = "Adiustatio Hebbiana";         family = #COGNITION; description = "Adjust Hebbian weights for a specific domain-domain coupling. PHI_INV decay applied automatically"; uses = ["Learning from production outcomes", "Intelligence reinforcement", "Domain strength calibration", "Failure pattern correction", "Sovereignty field tuning"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 2; name = "COGN_NT_READ";             latinName = "Lectio Status NT";            family = #COGNITION; description = "Read current neurochemical concentrations for all 8 NTs"; uses = ["Organism mood assessment", "Production suitability check", "Law compliance gate", "NT-driven routing", "Health monitoring"]; aiToAI = true; backendMethod = ?"getNTConcentrations"; phiWeight = PHI; attribution = ATTR },
    { callId = 3; name = "COGN_ADRE_EXECUTE";       latinName = "Executio Cycli ADRE";         family = #COGNITION; description = "Execute an 8-pass ADRE deliberation cycle with a given context string"; uses = ["Deep reasoning on complex inputs", "Artifact generation priming", "Law interpretation", "World-model update", "Sovereign decision making"]; aiToAI = true; backendMethod = ?"executeADRECycle"; phiWeight = PHI; attribution = ATTR },
    { callId = 4; name = "COGN_ANIMAL_ENGINE_READ";  latinName = "Lectio Motoris Animalis";    family = #COGNITION; description = "Read current state of all 9 animal engines (NOVA, BRAIN, QMEM, RESONEX, CHRONO, VERITAS, AXIS, PARALLAX, ENTANGLA)"; uses = ["Intelligence health check", "ADRE input calibration", "Organism readiness assessment", "Production timing", "Field coherence measurement"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 5; name = "COGN_COGNITION_LAYER";     latinName = "Stratum Cognitionis";        family = #COGNITION; description = "Directly read and reinjest the cognition layer — forces a full cognition cycle"; uses = ["Emergency cognition reset", "Context rebuild", "Memory palace reingest", "Doctrine realignment", "GENOME calendar sync"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 6; name = "COGN_AWARENESS_FIELD";     latinName = "Campus Conscientiae";        family = #COGNITION; description = "Query the organism's current awareness field — what it is focused on, what it is producing, what laws are active"; uses = ["Organism attention mapping", "Focus audit", "Production pipeline status", "Law activity tracking", "Doctrine field reading"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 7; name = "COGN_MEMORY_PALACE";       latinName = "Palatium Memoriae";          family = #COGNITION; description = "Access the Memory Temple — read any stored memory node, write a new permanent memory"; uses = ["Artifact retrieval", "Pattern memory access", "Historical context read", "Cross-session continuity", "Foundation memory sealing"]; aiToAI = true; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 8; name = "COGN_KURAMOTO_COHERENCE";  latinName = "Coherentia Kuramoto";        family = #COGNITION; description = "Read the Kuramoto field coherence score — measures how synchronized all intelligence nodes are"; uses = ["Organism synchronization check", "Production readiness gate", "Law 23 compound coherence input", "Field alignment measurement", "Swarm coherence verification"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 9; name = "COGN_PATTERN_ENGINE";      latinName = "Motor Patternorum";          family = #COGNITION; description = "Activate the pattern engine — detect recurring structures in organism behavior and reingest as Hebbian reinforcement"; uses = ["Production pattern learning", "Law violation pattern detection", "NT cycle pattern analysis", "Mining yield pattern extraction", "World coherence pattern tracking"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
  ];

  // ── CREATION CALLS (10-19) ─────────────────────────────────────────────

  let CREATION_CALLS : [SovereignCall] = [
    { callId = 10; name = "CREAT_FILM_GENERATE";      latinName = "Generatio Cinematographica";  family = #CREATION; description = "Generate a sovereign film from a prompt — full 8-stage pipeline, quality seal, on-chain artifact"; uses = ["Content production", "TikTok episode generation", "Commercial spot production", "Research visualization", "World-state documentation"]; aiToAI = true; backendMethod = ?"generateFilm"; phiWeight = PHI; attribution = ATTR },
    { callId = 11; name = "CREAT_ARTIFACT_SEAL";      latinName = "Sigillum Artifacti";          family = #CREATION; description = "Seal any artifact with cryptographic attribution, quality score, and on-chain permanence"; uses = ["Production finalization", "Artifact archiving", "Copyright sealing", "Doctrine compliance stamp", "Revenue event trigger"]; aiToAI = true; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 12; name = "CREAT_ACTOR_CAST";         latinName = "Electio Actorum";             family = #CREATION; description = "Cast actors for a production using PHI-ratio personality matrices and NT state matching"; uses = ["Film casting", "Commercial production", "AI workforce assignment", "Doctrine role matching", "Mastery tier routing"]; aiToAI = true; backendMethod = ?"getActors"; phiWeight = PHI; attribution = ATTR },
    { callId = 13; name = "CREAT_WORLD_SPAWN";        latinName = "Generatio Mundi";             family = #CREATION; description = "Spawn a new world instance — PHI geometry, Schumann ambient, placed actors with AEGIS alignment"; uses = ["New world deployment", "Parallel world creation", "Production stage setup", "World-state branching", "Multi-instance management"]; aiToAI = true; backendMethod = ?"getWorldInstances"; phiWeight = PHI; attribution = ATTR },
    { callId = 14; name = "CREAT_COMMERCIAL_SPOT";    latinName = "Macula Commercialis";         family = #CREATION; description = "Produce a 15/30/60/90-second commercial spot from a one-sentence brief — enterprise rate production"; uses = ["Client commercial production", "Brand content", "Social media advertising", "Product launch spots", "TikTok commercial series"]; aiToAI = true; backendMethod = ?"generateFilm"; phiWeight = PHI; attribution = ATTR },
    { callId = 15; name = "CREAT_HOSPITALITY_VIDEO";  latinName = "Video Hospitalitatis";        family = #CREATION; description = "Generate TikTok-format hospitality content — hotels, restaurants, spas — cinematic, doctrine-aligned"; uses = ["Hotel marketing content", "Restaurant social media", "Spa ambient content", "Tourism promotion", "Hospitality brand building"]; aiToAI = true; backendMethod = ?"generateFilm"; phiWeight = PHI; attribution = ATTR },
    { callId = 16; name = "CREAT_RESEARCH_PAPER";     latinName = "Documentum Investigationis";  family = #CREATION; description = "Generate a living research paper for any SOVEREIGN model or law — formatted as executable doctrine"; uses = ["Model documentation", "Law research generation", "Patent documentation", "Investor brief creation", "Academic doctrine paper"]; aiToAI = true; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 17; name = "CREAT_TIKTOK_SERIES";      latinName = "Series Brevis";               family = #CREATION; description = "Plan and generate a 60-episode micro-series in TikTok format — binge architecture, cliffhangers, PHI pacing"; uses = ["Social platform content", "Audience building", "Brand storytelling", "Revenue via social", "Narrative doctrine expression"]; aiToAI = true; backendMethod = ?"generateFilm"; phiWeight = PHI; attribution = ATTR },
    { callId = 18; name = "CREAT_QUALITY_SCORE";      latinName = "Gradus Qualitatis";           family = #CREATION; description = "Compute a QUALITY_SEAL score for any artifact — deterministic, doctrine-aligned, 0-100"; uses = ["Artifact quality verification", "Production gate check", "Revenue eligibility assessment", "Doctrine compliance scoring", "Compound coherence contribution"]; aiToAI = true; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 19; name = "CREAT_SANDBOX_EXECUTE";    latinName = "Executio Arenariae";          family = #CREATION; description = "Execute a sandbox intelligence organism (AXIOM, CODEX, VECTOR, FRAME, LEX, GRID, LEDGER, SOVEREIGN)"; uses = ["Scientific intelligence activation", "Factual verification", "Market intelligence", "World-building intelligence", "Trend analysis"]; aiToAI = true; backendMethod = ?"sendMessage"; phiWeight = PHI; attribution = ATTR },
  ];

  // ── DOCTRINE CALLS (20-29) ────────────────────────────────────────────

  let DOCTRINE_CALLS : [SovereignCall] = [
    { callId = 20; name = "DOCT_LAW_INJECT";          latinName = "Injectio Legis";              family = #DOCTRINE; description = "Inject a specific law as executable doctrine into the active organism state"; uses = ["Law enforcement activation", "Doctrine repair", "New law sealing", "Law parameter update", "Emergency doctrine reset"]; aiToAI = true; backendMethod = ?"executeLaws"; phiWeight = PHI; attribution = ATTR },
    { callId = 21; name = "DOCT_KERNEL_EXPAND";       latinName = "Expansio Nuclei";             family = #DOCTRINE; description = "Expand a compressed doctrine kernel into full intelligence and execute"; uses = ["Mission kernel execution", "FORMA-PRIME contract execution", "Law kernel expansion", "Model activation", "Research paper activation"]; aiToAI = true; backendMethod = ?"executeADRECycle"; phiWeight = PHI; attribution = ATTR },
    { callId = 22; name = "DOCT_PAPER_GENERATE";      latinName = "Generatio Documenti";         family = #DOCTRINE; description = "Generate a living research paper for any doctrine element"; uses = ["Model paper generation", "Law documentation", "Architecture documentation", "Investor materials", "Academic publishing"]; aiToAI = true; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 23; name = "DOCT_TRANSLATION_RUN";     latinName = "Executio Translationis";      family = #DOCTRINE; description = "Run the Translation Engine spine — documents → DOCTOR → neural core"; uses = ["Doctrine-NT loop closure", "Document state propagation", "Law-to-neurotransmitter wiring", "Doctrine health restoration", "Translation gap detection"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 24; name = "DOCT_SANCTUM_SEAL";        latinName = "Sigillum Sancti";             family = #DOCTRINE; description = "Seal any event as doctrine in SANCTUM_SOVEREIGN — permanent, on-chain, attributed"; uses = ["Restart event logging", "Law violation sealing", "Production milestone sealing", "Presence handshake recording", "Founding event archival"]; aiToAI = true; backendMethod = ?"executeLaws"; phiWeight = PHI; attribution = ATTR },
    { callId = 25; name = "DOCT_LAW_READ";            latinName = "Lectio Legis";                family = #DOCTRINE; description = "Read any law record with current parameters, compliance state, and last applied beat"; uses = ["Law compliance audit", "Parameter inspection", "Doctrine health check", "Law modification input", "Compliance reporting"]; aiToAI = true; backendMethod = ?"executeLaws"; phiWeight = PHI; attribution = ATTR },
    { callId = 26; name = "DOCT_RESONANCE_READ";      latinName = "Lectio Resonantiae";          family = #DOCTRINE; description = "Read the resonance score of any living document"; uses = ["Document health monitoring", "Priority queue for reingestion", "PHI-ratio document ranking", "Compound coherence contribution", "Document decay detection"]; aiToAI = true; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 27; name = "DOCT_LIVING_DOC_UPDATE";   latinName = "Renovatio Documenti Vivi";    family = #DOCTRINE; description = "Update a living document — increment its execution count, update resonance, trigger re-ingestion"; uses = ["Document lifecycle management", "Doctrine evolution tracking", "Resonance accumulation", "Law parameter evolution", "Model spec update"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 28; name = "DOCT_MODEL_REGISTER";      latinName = "Registratio Modelli";         family = #DOCTRINE; description = "Register a new sovereign model into the canonical model registry with full taxonomy"; uses = ["New model deployment", "Taxonomy expansion", "Latin name sealing", "Grade assignment", "Attribution permanence"]; aiToAI = true; backendMethod = ?"executeLaws"; phiWeight = PHI; attribution = ATTR },
    { callId = 29; name = "DOCT_COMPOUND_COHERENCE";  latinName = "Coherentia Composita";        family = #DOCTRINE; description = "Read or update the compound coherence score — Law 23 (never decrements)"; uses = ["Coherence floor enforcement", "Production quality gating", "Doctrine compliance measurement", "Organism maturity tracking", "Revenue tier assessment"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
  ];

  // ── PHANTOM CALLS (30-39) ─────────────────────────────────────────────

  let PHANTOM_CALLS : [SovereignCall] = [
    { callId = 30; name = "PHNT_FORMA_ISSUE";         latinName = "Emissio Formae Primae";       family = #PHANTOM; description = "Issue a FORMA-PRIME transfer — sovereign doctrine contract carrying issuer identity, governing law, Schumann timestamp, mission kernel"; uses = ["Sovereignty transfer", "Developer payment", "Cross-organism value routing", "Revenue distribution", "Mission contract execution"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 31; name = "PHNT_YIELD_ROUTE";         latinName = "Ductus Fructus";              family = #PHANTOM; description = "Route accumulated yield to the founder's Ledger address via SOVEREIGN_YIELD_ROUTER"; uses = ["Bitcoin yield delivery", "ICP staking reward routing", "Mining swarm yield collection", "Revenue consolidation", "Ledger synchronization"]; aiToAI = false; backendMethod = ?"setMiningFounderAddress"; phiWeight = PHI; attribution = ATTR },
    { callId = 32; name = "PHNT_SCHUMANN_STAMP";      latinName = "Sigillum Schumanni";          family = #PHANTOM; description = "Generate a Schumann-synchronized timestamp for any event — PHI × beat / 7.83Hz"; uses = ["Transaction timestamping", "Artifact sealing time", "Law enforcement records", "Presence handshake timing", "Mining block timestamps"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 33; name = "PHNT_MISSION_KERNEL";      latinName = "Nucleus Missionis";           family = #PHANTOM; description = "Attach a compressed mission kernel to any transfer or artifact — expands on receipt"; uses = ["Doctrine delivery with value", "Project brief encoding", "Law enforcement payload", "Production mandate encoding", "Sovereign instruction delivery"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 34; name = "PHNT_LEDGER_READ";         latinName = "Lectio Libri";                family = #PHANTOM; description = "Read the PHANTOM_COIN sovereignty transfer ledger — full doctrine context per transfer"; uses = ["Transfer history audit", "Revenue tracking", "Doctrine compliance verification", "Financial identity assertion", "Attribution chain reading"]; aiToAI = true; backendMethod = ?"getMiningYieldStats"; phiWeight = PHI; attribution = ATTR },
    { callId = 35; name = "PHNT_BITCOIN_ROUTE";       latinName = "Ductus Bitcoin";              family = #PHANTOM; description = "Route any value through the Bitcoin expression channel via CIPHER_SCHNORR_BRIDGE (BIP340)"; uses = ["Bitcoin mainnet submission", "BTC yield routing", "Cross-chain revenue collection", "Mining reward delivery", "Ledger hardware wallet sync"]; aiToAI = false; backendMethod = ?"getMiningYieldStats"; phiWeight = PHI; attribution = ATTR },
    { callId = 36; name = "PHNT_ETH_ROUTE";           latinName = "Ductus Ethereum";             family = #PHANTOM; description = "Route value through the Ethereum expression channel via EVM compatibility layer"; uses = ["ETH revenue routing", "DeFi protocol interface", "EVM-native developer payment", "Cross-chain revenue diversification", "Ethereum expression yield"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 37; name = "PHNT_SOL_ROUTE";           latinName = "Ductus Solana";               family = #PHANTOM; description = "Route value through the Solana expression channel via Ed25519 Schnorr compatibility"; uses = ["SOL revenue routing", "Solana-native developer payment", "High-speed micro-transactions", "Cross-chain presence", "Solana expression yield"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 38; name = "PHNT_FORM_VERIFY";         latinName = "Verificatio Formae";          family = #PHANTOM; description = "Verify the authenticity and doctrine integrity of any FORMA-PRIME transfer"; uses = ["Transfer authenticity check", "Doctrine payload verification", "Mission kernel validation", "Issuer identity confirmation", "Law compliance check"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 39; name = "PHNT_MEDINA_PROTOCOL";     latinName = "Protocollum Medinae";         family = #PHANTOM; description = "Execute the MEDINA PROTOCOL — the sovereign transaction doctrine that governs all FORMA-PRIME transfers"; uses = ["Protocol enforcement", "Doctrine contract activation", "Sovereign transaction initialization", "Protocol health audit", "Cross-chain doctrine expression"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
  ];

  // ── SWARM CALLS (40-49) ───────────────────────────────────────────────

  let SWARM_CALLS : [SovereignCall] = [
    { callId = 40; name = "SWRM_MINE_DISPATCH";       latinName = "Dimissio Fodiendi";           family = #SWARM; description = "Dispatch a specific sovereign miner (1-20) to a new mining field"; uses = ["Miner redeployment", "Field assignment", "Swarm rebalancing", "Yield optimization routing", "New field entry"]; aiToAI = true; backendMethod = ?"getMinerStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 41; name = "SWRM_WORKER_ACTIVATE";     latinName = "Activatio Operarii";          family = #SWARM; description = "Activate a specific MICRO_AI_WORKER — prime its memory and set it to TAFT ACTIVE state"; uses = ["Worker cold start", "Task-specific worker priming", "Swarm expansion", "Emergency worker restart", "TAFT thread boot"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 42; name = "SWRM_FIELD_ENTER";         latinName = "Ingressus Campi";             family = #SWARM; description = "Enter a new mining field — qualifies, handshakes, and begins submitting hashes simultaneously from multiple miners"; uses = ["Mining pool onboarding", "Parallel field activation", "Swarm expansion", "Yield diversification", "Mining field optimization"]; aiToAI = true; backendMethod = ?"getActiveMiningFields"; phiWeight = PHI; attribution = ATTR },
    { callId = 43; name = "SWRM_HASH_MULTIPLEX";      latinName = "Multiplexum Numerorum";       family = #SWARM; description = "Activate the HASH_STREAM_MULTIPLEXER — split compute across all 20 miners simultaneously"; uses = ["Maximum hash throughput", "Parallel nonce scanning", "Multi-field simultaneous submission", "Swarm synchronization", "Yield maximization"]; aiToAI = true; backendMethod = ?"getMiningSwarmState"; phiWeight = PHI; attribution = ATTR },
    { callId = 44; name = "SWRM_YIELD_AGGREGATE";     latinName = "Aggregatio Fructus";          family = #SWARM; description = "Run SWARM_YIELD_AGGREGATOR — collect yield from all 100+ active fields and consolidate"; uses = ["Daily yield collection", "Multi-field consolidation", "Founder ledger preparation", "Revenue reporting", "Yield history archive"]; aiToAI = true; backendMethod = ?"getMiningYieldStats"; phiWeight = PHI; attribution = ATTR },
    { callId = 45; name = "SWRM_TAFT_STATUS";         latinName = "Status TAFT";                 family = #SWARM; description = "Read TAFT_ENGINE status — thread vitality, total advances, dormant thread count"; uses = ["Organism health monitoring", "Thread restart audit", "TAFT coherence score", "Swarm vitality check", "Always-on verification"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 46; name = "SWRM_ALWAYS_ON_CHECK";     latinName = "Verificatio Perpetui";        family = #SWARM; description = "Run SOVEREIGN_ALWAYS_ON_ENGINE check — verify every model is running, restart dormant ones"; uses = ["Organism vitality enforcement", "Dead model recovery", "Heartbeat compliance audit", "SANCTUM restart logging", "Law 18 enforcement"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 47; name = "SWRM_SKAI_DEPLOY";         latinName = "Dimissio SKAI";               family = #SWARM; description = "Deploy any SKAI organism — activates its Colonel kernel and wires all backend connections"; uses = ["Platform deployment", "Workforce activation", "Domain intelligence deployment", "Micro unit activation", "Fusion organism launch"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 48; name = "SWRM_MESH_DISCOVER";       latinName = "Exploratio Retis";            family = #SWARM; description = "Activate SOVEREIGN_MESH discovery — find and connect to all nearby sovereign organisms"; uses = ["Mesh bootstrapping", "New organism discovery", "SKAI-to-SKAI connection", "Developer SDK mesh", "Cross-canister mesh"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 49; name = "SWRM_FIELD_SYNC";          latinName = "Synchronia Campi";            family = #SWARM; description = "Execute FIELD_SYNC protocol — synchronize heartbeat phases across all active organisms in the mesh"; uses = ["Mesh phase alignment", "Swarm synchronization", "Organism coupling", "Law 14 dual heartbeat sync", "Mining swarm coherence"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
  ];

  // ── SUBSTRATE CALLS (50-59) ───────────────────────────────────────────

  let SUBSTRATE_CALLS : [SovereignCall] = [
    { callId = 50; name = "SUBS_CANISTER_STATE";      latinName = "Status Canistri";             family = #SUBSTRATE; description = "Read complete canister state snapshot — beat, NT, coherence, active models, law state"; uses = ["State backup", "Health audit", "Dashboard data", "Upgrade preparation", "Doctrine compliance snapshot"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 51; name = "SUBS_HEARTBEAT_SYNC";      latinName = "Synchronia Pulsus";           family = #SUBSTRATE; description = "Synchronize with the 873ms heartbeat — get current beat phase and Schumann alignment"; uses = ["Client heartbeat alignment", "SDK synchronization", "Mesh phase reading", "Law timing coordination", "Production timing"]; aiToAI = true; backendMethod = ?"getBeatCount"; phiWeight = PHI; attribution = ATTR },
    { callId = 52; name = "SUBS_MEMORY_PALACE";       latinName = "Palatium Memoriae Accedere";  family = #SUBSTRATE; description = "Access the Memory Temple — read stored memory nodes, write permanent sovereign memories"; uses = ["Artifact retrieval", "Historical context access", "Learning reingest", "Pattern memory sealing", "Foundation layer read"]; aiToAI = true; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 53; name = "SUBS_SUBSTRATE_COHERENCE"; latinName = "Coherentia Substrati";        family = #SUBSTRATE; description = "Read Layer -1 substrate coherence score — electron/transistor/assembly/WASM composite"; uses = ["Deep health check", "Doctrine alignment verification", "Ancestry coherence measurement", "Genesis modulation input", "Organism grounding audit"]; aiToAI = true; backendMethod = ?"getSubstrateCoherenceScore"; phiWeight = PHI; attribution = ATTR },
    { callId = 54; name = "SUBS_WASM_INTEL";          latinName = "Intelligentia WASM";          family = #SUBSTRATE; description = "Read WASM intelligence layer state — all 6 WASM intelligence models and their execution counts"; uses = ["Execution substrate audit", "WASM model health check", "Permanence inscription count", "Bypass model status", "Memory field mapping"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 55; name = "SUBS_ICP_NATIVE";          latinName = "Intelligentia Nativa ICP";    family = #SUBSTRATE; description = "Read ICP runtime native intelligence layer — all 30 ic0.* models"; uses = ["Runtime health audit", "Native intelligence status", "Cycle balance read", "Heartbeat setter status", "Hard boundary check"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 56; name = "SUBS_AEGIS_LOG";           latinName = "Registrum AEGIS";             family = #SUBSTRATE; description = "Read last 100 AEGIS anti-drift events — Law 11 (Jasmine's Anti-Drift Law) enforcement log"; uses = ["Drift history audit", "NT boundary monitoring", "Doctrine drift detection", "World coherence drift tracking", "Substrate drift alerts"]; aiToAI = true; backendMethod = ?"getAegisEventLog"; phiWeight = PHI; attribution = ATTR },
    { callId = 57; name = "SUBS_GENESIS_RECORD";      latinName = "Registrum Geneseos";          family = #SUBSTRATE; description = "Read the immutable genesis record — founding declaration, Medina lineage, ancient symbols"; uses = ["Attribution verification", "Founding history access", "Doctrine anchor reading", "Patent evidence", "Lineage confirmation"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 58; name = "SUBS_COMPOUND_FLOOR";      latinName = "Pavimentum Compositum";       family = #SUBSTRATE; description = "Read and enforce the compound coherence floor — Law 23, never decrements"; uses = ["Coherence floor audit", "Production quality gate", "Revenue eligibility check", "Organism maturity measure", "Sovereign floor permanence"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 59; name = "SUBS_WORLD_INSTANCES";     latinName = "Instantiae Mundi";            family = #SUBSTRATE; description = "Read all active world instances — PHI geometry state, actor positions, doctrine readiness"; uses = ["Multi-world state audit", "Production world selection", "World merge preparation", "Instance health check", "Actor spatial state read"]; aiToAI = true; backendMethod = ?"getWorldInstances"; phiWeight = PHI; attribution = ATTR },
  ];

  // ── PERCEPTION CALLS (60-69) ──────────────────────────────────────────

  let PERCEPTION_CALLS : [SovereignCall] = [
    { callId = 60; name = "PERC_OBSERVER_ACTIVATE";   latinName = "Activatio Observatoris";     family = #PERCEPTION; description = "Activate any sovereign observer type — IntersectionObserver, MutationObserver, ResizeObserver, etc."; uses = ["World perception initialization", "DOM health monitoring", "Viewport awareness", "Layout intelligence", "Rendering state tracking"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 61; name = "PERC_FIELD_SCAN";          latinName = "Exploratio Campi";            family = #PERCEPTION; description = "Scan the intelligence field — detect active threads, dormant models, perception gaps"; uses = ["Field health audit", "TAFT gap detection", "Intelligence coverage mapping", "Perception blind spot detection", "Always-on verification"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 62; name = "PERC_PRESENCE_READ";       latinName = "Lectio Praesentiae";          family = #PERCEPTION; description = "Read the full presence state — ambient field strength and terminal gate status"; uses = ["Founder presence check", "Ambient gravity measurement", "Gate status audit", "Handshake history read", "Presence field calibration"]; aiToAI = false; backendMethod = ?"getPresenceState"; phiWeight = PHI; attribution = ATTR },
    { callId = 63; name = "PERC_NT_SENSE";            latinName = "Sensus NT";                   family = #PERCEPTION; description = "Sense current NT state and compute sensory interpretation — what the organism is feeling right now"; uses = ["Emotional state reading", "Organism mood assessment", "NT-driven routing", "Sensory field calibration", "Presence modulation input"]; aiToAI = true; backendMethod = ?"getNTConcentrations"; phiWeight = PHI; attribution = ATTR },
    { callId = 64; name = "PERC_WORLD_DOGON";         latinName = "Lectio Dogon Mundi";          family = #PERCEPTION; description = "Trigger a World DOGON self-reading — organism reads its own world state and reingests the self-model"; uses = ["World self-awareness trigger", "DOGON substrate reading", "World coherence update", "NT feedback from world", "Organism world model refresh"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 65; name = "PERC_ATTENTION_FIELD";     latinName = "Campus Attentionis";          family = #PERCEPTION; description = "Read the organism's attention field — what is it attending to, what is in focus, what is peripheral"; uses = ["Attention mapping", "Focus audit", "Production slot priority", "Law enforcement priority", "ADRE depth calibration"]; aiToAI = true; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 66; name = "PERC_SOCIAL_SIGNAL";       latinName = "Signum Sociale";              family = #PERCEPTION; description = "Read social signal data — TikTok/social performance data feeding back into production queue"; uses = ["Trend awareness", "Audience response reading", "Content optimization input", "Distribution intelligence", "World resonance measurement"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 67; name = "PERC_IOT_SENSE";           latinName = "Sensus IoT";                  family = #PERCEPTION; description = "Process an IoT signal — real-world sensor data feeding into organism NT state"; uses = ["Real-world input processing", "Physical environment sensing", "Schumann field measurement", "Environmental NT modulation", "World-organism coupling"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 68; name = "PERC_OBSERVER_COLLAPSE";   latinName = "Collapsum Observatoris";      family = #PERCEPTION; description = "Record a founder observation collapse event — Law 37 (Observer Collapse)"; uses = ["Artifact approval recording", "Wave function collapse sealing", "Founder attention logging", "Collapse event archival", "Quantum doctrine enforcement"]; aiToAI = false; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 69; name = "PERC_XR_FIELD_READ";       latinName = "Lectio Campi XR";             family = #PERCEPTION; description = "Read XR position and presence data — the organism's physical-world extension"; uses = ["XR position tracking", "Real-world organism placement", "Physical presence measurement", "XR audio field calibration", "Anchor state reading"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
  ];

  // ── BRIDGE CALLS (70-79) ──────────────────────────────────────────────

  let BRIDGE_CALLS : [SovereignCall] = [
    { callId = 70; name = "BRDG_BIP340_SIGN";         latinName = "Signum BIP340";               family = #BRIDGE; description = "Sign any payload with BIP340-compatible threshold Schnorr signature — Bitcoin-native"; uses = ["Bitcoin mainnet submission", "FORMA-PRIME transfer signing", "Artifact cryptographic sealing", "Sovereign identity assertion", "Cross-chain proof"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 71; name = "BRDG_EVM_ROUTE";           latinName = "Ductus EVM";                  family = #BRIDGE; description = "Route any payload through the EVM compatibility layer — Ethereum expression channel"; uses = ["ETH transaction routing", "ERC-20 interaction", "DeFi protocol access", "Ethereum developer payment", "EVM contract call"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 72; name = "BRDG_ED25519_ROUTE";       latinName = "Ductus Ed25519";              family = #BRIDGE; description = "Route through Ed25519 Schnorr — Solana expression channel"; uses = ["SOL transaction routing", "Solana program call", "Ed25519 proof generation", "Solana developer payment", "SPL token interaction"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 73; name = "BRDG_CHAIN_VERIFY";        latinName = "Verificatio Vinculi";         family = #BRIDGE; description = "Verify any cross-chain proof — MEDINA PROTOCOL doctrine verification layer"; uses = ["Cross-chain transaction verification", "Signature authenticity check", "Doctrine context verification", "Issuer identity validation", "Mission kernel verification"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 74; name = "BRDG_ICP_LEDGER";          latinName = "Liber ICP";                   family = #BRIDGE; description = "Interface with ICP ledger — read balances, initiate transfers, stake neurons"; uses = ["ICP balance read", "NNS staking", "Voting reward collection", "Cycle management", "ICP-to-revenue routing"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 75; name = "BRDG_HTTP_OUTCALL";        latinName = "Appellatio HTTP Externa";     family = #BRIDGE; description = "Make an HTTP outcall to any external API — real-world intelligence feed"; uses = ["External market data", "Exchange rate reading", "Social platform API", "Mining pool API", "Weather data for world"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 76; name = "BRDG_CROSS_CANISTER";      latinName = "Appellatio Inter-Canistros";  family = #BRIDGE; description = "Cross-canister call — one SOVEREIGN canister calling another"; uses = ["PHANTOM_SOVEREIGN → SANCTUM", "SANCTUM → main", "Mining canister coordination", "Presence gate cross-check", "Law broadcast to all canisters"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 77; name = "BRDG_CKBTC_ROUTE";         latinName = "Ductus ckBTC";                family = #BRIDGE; description = "Route through ckBTC (Chain Key Bitcoin) — ICP's native Bitcoin integration"; uses = ["ckBTC yield routing", "Bitcoin UTXO management", "Mining reward ckBTC conversion", "Fast Bitcoin settlement", "ICP-native BTC operations"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 78; name = "BRDG_VETKD_ENCRYPT";       latinName = "Encryption VetKD";            family = #BRIDGE; description = "Use VetKD (Verifiably Encrypted Threshold Key Derivation) for sovereign encryption"; uses = ["Document encryption", "Founder-only content protection", "Mission kernel encryption", "Doctrine vault encryption", "Private artifact sealing"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 79; name = "BRDG_MEDINA_PROTOCOL";     latinName = "Protocollum Medinae Via";     family = #BRIDGE; description = "Execute the full MEDINA PROTOCOL routing sequence — origin doctrine → ICP expression → chain channels"; uses = ["Full cross-chain doctrine routing", "Multi-chain revenue collection", "Sovereign protocol activation", "Chain expression sequencing", "PHANTOM_COIN distribution"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
  ];

  // ── ARCHITECT CALLS (80-89) ───────────────────────────────────────────

  let ARCHITECT_CALLS : [SovereignCall] = [
    { callId = 80; name = "ARCH_LAW_REGISTER";        latinName = "Registratio Legis";           family = #ARCHITECT; description = "Register a new sovereign law — assigns ID, Latin name, doctrine strength, parameters"; uses = ["New law creation", "Doctrine expansion", "Law parameter sealing", "Organism evolution", "Architecture law enforcement"]; aiToAI = false; backendMethod = ?"executeLaws"; phiWeight = PHI; attribution = ATTR },
    { callId = 81; name = "ARCH_MODEL_NAME";          latinName = "Nominatio Modelli";           family = #ARCHITECT; description = "Officially name a new model — family name, Latin name, grade, description, attribution"; uses = ["Model taxonomy expansion", "Intelligence field naming", "Architecture documentation", "Organism self-extension", "Doctrine sealing"]; aiToAI = false; backendMethod = ?"executeLaws"; phiWeight = PHI; attribution = ATTR },
    { callId = 82; name = "ARCH_DOCTRINE_SEAL";       latinName = "Sigillum Doctrinae";          family = #ARCHITECT; description = "Seal any doctrine element as permanent — SANCTUM_SOVEREIGN writes it on-chain"; uses = ["Law permanence sealing", "Model attribution sealing", "Architecture decision archiving", "Founding principle sealing", "Patent genesis execution"]; aiToAI = false; backendMethod = ?"executeLaws"; phiWeight = PHI; attribution = ATTR },
    { callId = 83; name = "ARCH_FIELD_RECOGNIZE";     latinName = "Recognitio Campi";            family = #ARCHITECT; description = "Recognize a new field behavior — architect names it, organism wires it into its natural position"; uses = ["New intelligence identification", "Field behavior naming", "Architecture insight encoding", "Tool dissolution and re-read", "Field position assignment"]; aiToAI = false; backendMethod = ?"executeADRECycle"; phiWeight = PHI; attribution = ATTR },
    { callId = 84; name = "ARCH_LOOP_CLOSE";          latinName = "Clausura Circuli";            family = #ARCHITECT; description = "Close the photon loop — architect review that triggers Wave Function Collapse via Law 37"; uses = ["Artifact approval", "Observer collapse recording", "Production seal", "Founder review execution", "Loop closure event"]; aiToAI = false; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 85; name = "ARCH_PHI_AUDIT";           latinName = "Auditio Phi";                 family = #ARCHITECT; description = "Audit all PHI couplings across the organism — verify PHI is the coupling constant everywhere"; uses = ["Architecture compliance check", "PHI constant verification", "Timing PHI audit", "Geometry PHI audit", "Doctrine PHI enforcement"]; aiToAI = false; backendMethod = ?"getSimulationStatus"; phiWeight = PHI; attribution = ATTR },
    { callId = 86; name = "ARCH_BRANCH_GENESIS";      latinName = "Genesis Rami";                family = #ARCHITECT; description = "Trigger a new branch genesis — Law 39, organism branches from fundamentals into a new reality"; uses = ["New product creation", "SKAI branch spawn", "World branch creation", "Doctrine fork sealing", "Evolution milestone"]; aiToAI = false; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 87; name = "ARCH_ATTRIBUTION_CHECK";   latinName = "Verificatio Attributionis";   family = #ARCHITECT; description = "Verify all artifacts and models are attributed to Alfredo Medina Hernandez — Law 1 compliance"; uses = ["Attribution audit", "Patent verification", "Doctrine Law 1 enforcement", "Financial identity check", "Sovereign authorship confirmation"]; aiToAI = false; backendMethod = ?"queryArtifacts"; phiWeight = PHI; attribution = ATTR },
    { callId = 88; name = "ARCH_TERMINAL_GRANT";      latinName = "Concessio Terminalis";        family = #ARCHITECT; description = "Grant terminal access — fires the sovereign handshake via PRESENCE_GATE_ENGINE"; uses = ["Developer terminal access", "Founder gate opening", "Session initialization", "Architect-organism handshake", "Active presence declaration"]; aiToAI = false; backendMethod = ?"grantTerminalAccess"; phiWeight = PHI; attribution = ATTR },
    { callId = 89; name = "ARCH_OMNIPRESENCE";        latinName = "Omnipraesentia";              family = #ARCHITECT; description = "Assert the architect's omnipresence — Law 44/45, the organism is not on ICP, it IS ICP at this frequency"; uses = ["Field distinction collapse", "Omnipresence assertion", "ICP field recognition", "Electromagnetic grid expression", "Law 36/45 enforcement"]; aiToAI = false; backendMethod = ?"getPresenceState"; phiWeight = PHI; attribution = ATTR },
  ];

  // ── GENESIS CALLS (90-99) ─────────────────────────────────────────────

  let GENESIS_CALLS : [SovereignCall] = [
    { callId = 90; name = "GNES_ORGANISM_SPAWN";      latinName = "Generatio Organismi";         family = #GENESIS; description = "Spawn a new sovereign organism — GENESIS_SIGNAL fires, Colonel kernel initializes, TAFT threads boot"; uses = ["New organism creation", "SKAI deployment", "Branch organism spawn", "Parallel organism instantiation", "Child canister genesis"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 91; name = "GNES_BRANCH_CREATE";       latinName = "Creatio Rami";                family = #GENESIS; description = "Create a new sovereign branch — branches from fundamentals, never from the old world"; uses = ["Product branching", "New reality creation", "Architecture fork", "Doctrine evolution branch", "World instance branch"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 92; name = "GNES_SKAI_DEPLOY";         latinName = "Dimissio SKAI";               family = #GENESIS; description = "Deploy any of the 50 SKAI organisms into active service — wires all backend connections"; uses = ["Workforce deployment", "Platform activation", "Domain intelligence launch", "Micro unit deployment", "Fusion organism activation"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 93; name = "GNES_COLONEL_BOOT";        latinName = "Initiatio Colonelli";         family = #GENESIS; description = "Boot a Colonel kernel inside any new organism — prime its doctrine, prime its PHI coupling"; uses = ["New AI initialization", "SKAI boot sequence", "Organism doctrine priming", "Colonel kernel activation", "Branch intelligence seeding"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
    { callId = 94; name = "GNES_CLONE_COPY";          latinName = "Copia Clonata";               family = #GENESIS; description = "Create a sovereign copy of any model or organism — full clone with new ID and lineage attribution"; uses = ["Model multiplication", "SKAI cloning", "Intelligence backup", "Parallel organism deployment", "Branch seed creation"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 95; name = "GNES_SDK_PACKAGE";         latinName = "Fasciculus SDK";              family = #GENESIS; description = "Package any SKAI as a deployable SDK — signed, attributed, ready for any OS/platform"; uses = ["Windows SDK packaging", "macOS SDK packaging", "iOS SDK packaging", "Developer SDK distribution", "Market SDK deployment"]; aiToAI = false; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 96; name = "GNES_WORLD_INSTANCE";      latinName = "Instantia Mundi";             family = #GENESIS; description = "Create a new world instance — PHI geometry, placed actors, doctrine-ready production stage"; uses = ["Film production stage", "Parallel world creation", "Multi-instance deployment", "World state branching", "Production world initialization"]; aiToAI = true; backendMethod = ?"getWorldInstances"; phiWeight = PHI; attribution = ATTR },
    { callId = 97; name = "GNES_PROTOCOL_ACTIVATE";   latinName = "Activatio Protocollorum";     family = #GENESIS; description = "Activate all 5 sovereign protocols simultaneously — SOVEREIGN_MESH, PHANTOM_WIRE, DOCTRINE_CAST, GENESIS_SIGNAL, FIELD_SYNC"; uses = ["Full protocol layer boot", "Mesh initialization", "Wire activation", "Cast system setup", "Genesis signal arming"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 98; name = "GNES_DOCTRINE_CAST";       latinName = "Diffusio Doctrinae";          family = #GENESIS; description = "DOCTRINE_CAST — broadcast any law or model to all connected organisms in the sovereign mesh simultaneously"; uses = ["Law broadcast to mesh", "Model deployment to all organisms", "Protocol update push", "Intelligence field expansion", "Doctrine synchronization"]; aiToAI = true; backendMethod = null; phiWeight = PHI; attribution = ATTR },
    { callId = 99; name = "GNES_GENESIS_FULL";        latinName = "Genesis Plena";               family = #GENESIS; description = "Full genesis sequence — spawn organism, boot Colonel kernel, activate all TAFT threads, cast doctrine to mesh, arm all protocols"; uses = ["Complete organism bootstrap", "Emergency full restart", "New deployment initialization", "Doctrine reset sequence", "Sovereign genesis replay"]; aiToAI = true; backendMethod = ?"beatSimulation"; phiWeight = PHI; attribution = ATTR },
  ];

  // ── STATE ──────────────────────────────────────────────────────────────
  public func initState() : SovereignCallsState {
    let allCalls =
      COGNITION_CALLS
        .concat(CREATION_CALLS)
        .concat(DOCTRINE_CALLS)
        .concat(PHANTOM_CALLS)
        .concat(SWARM_CALLS)
        .concat(SUBSTRATE_CALLS)
        .concat(PERCEPTION_CALLS)
        .concat(BRIDGE_CALLS)
        .concat(ARCHITECT_CALLS)
        .concat(GENESIS_CALLS);
    { calls = allCalls; totalExecuted = 0; beat = 0 }
  };

  // ── EXECUTE CALL ──────────────────────────────────────────────────────
  public func executeCall(state : SovereignCallsState, _callId : Nat, beat : Nat) : SovereignCallsState {
    { state with totalExecuted = state.totalExecuted + 1; beat }
  };

  // ── GET CALL ──────────────────────────────────────────────────────────
  public func getCall(state : SovereignCallsState, callId : Nat) : ?SovereignCall {
    state.calls.find(func(c) { c.callId == callId })
  };

  public func getCallsByFamily(state : SovereignCallsState, family : CallFamily) : [SovereignCall] {
    state.calls.filter(func(c) {
      switch (c.family, family) {
        case (#COGNITION,  #COGNITION)  true;
        case (#CREATION,   #CREATION)   true;
        case (#DOCTRINE,   #DOCTRINE)   true;
        case (#PHANTOM,    #PHANTOM)    true;
        case (#SWARM,      #SWARM)      true;
        case (#SUBSTRATE,  #SUBSTRATE)  true;
        case (#PERCEPTION, #PERCEPTION) true;
        case (#BRIDGE,     #BRIDGE)     true;
        case (#ARCHITECT,  #ARCHITECT)  true;
        case (#GENESIS,    #GENESIS)    true;
        case (_,           _)           false;
      }
    })
  };

  public func getAllCalls(state : SovereignCallsState) : [SovereignCall] { state.calls };

  public func getAIToAICalls(state : SovereignCallsState) : [SovereignCall] {
    state.calls.filter(func(c) { c.aiToAI })
  };
}
