// types/sandboxOrganisms.mo
// Type definitions for the 8 SOVEREIGN Sandboxed Intelligence Organisms:
//   AXIOM · CODEX · VECTOR · FRAME · LEX · GRID · LEDGER · SOVEREIGN_GOV
//
// Each organism is fully isolated — no cross-contamination with the 43-core
// substrate, VELA ring, OMNIS, or film pipeline state.
//
// PHI = 1.6180339887 | S0_FLOOR = 0.75
// Authored by Alfredo Medina Hernandez — immutable, sealed on-chain.
// Dedicated to his sister.

module {

  // ── ATTRIBUTION ───────────────────────────────────────────────────────────
  public let ATTRIBUTION : Text = "Alfredo Medina Hernandez";
  public let LAW         : Text = "Law of Medina";
  public let PHI         : Float = 1.6180339887;
  public let S0_FLOOR    : Float = 0.75;

  // ── ORGANISM IDENTIFIER ────────────────────────────────────────────────────
  // #axiom       — Scientific intelligence (arXiv, research papers)
  // #codex       — Cross-domain knowledge synthesis
  // #vector      — Market intelligence (crypto, equities, commodities)
  // #frame       — Geospatial + climate signals
  // #lex         — Legal / regulatory monitoring
  // #grid        — Tech infrastructure + open-source ecosystem
  // #ledger      — Internal financial accounting + P&L
  // #sovereignGov— Meta-governance: oversees all 8, enforces doctrine alignment
  public type SandboxOrganismId = {
    #axiom;
    #codex;
    #vector;
    #frame;
    #lex;
    #grid;
    #ledger;
    #sovereignGov;
  };

  // ── SANDBOX SIGNAL ─────────────────────────────────────────────────────────
  // A single intelligence signal generated by a sandbox organism cycle.
  // doctrineAlignment ∈ [0.0, 1.0] via PHI-ratio scoring.
  // routedToFilmPipeline = true once SOVEREIGN_GOV has approved and queued it.
  public type SandboxSignal = {
    id                  : Text;
    source              : SandboxOrganismId;
    category            : Text;
    headline            : Text;
    data                : Text;
    doctrineAlignment   : Float;
    timestamp           : Int;
    routedToFilmPipeline: Bool;
  };

  // ── RESEARCH DOCUMENT ──────────────────────────────────────────────────────
  // An exportable research artifact produced by a sandbox organism.
  // genesisAnchor = PHI-ratio hash of (orgId concat timestamp).
  // pdfUrl is populated when the document is sealed to ARES_ARCHIVE.
  public type SandboxResearchDocument = {
    id                   : Text;
    title                : Text;
    date                 : Int;
    genesisAnchor        : Text;
    organismId           : SandboxOrganismId;
    researchSummary      : Text;
    keyFindings          : [Text];
    doctrineAlignmentScore: Float;
    attribution          : Text;
    onChainSealId        : Text;
    pdfUrl               : ?Text;
  };

  // ── ORGANISM STATE ──────────────────────────────────────────────────────────
  // Full state record for one sandboxed organism.
  // masteryLevel advances at Fibonacci cycle counts: 1,2,3,5,8,13,21,34,55,89…
  public type SandboxOrganismState = {
    id               : SandboxOrganismId;
    name             : Text;
    description      : Text;
    masteryLevel     : Nat;
    lastCycleTime    : Int;
    cycleCount       : Nat;
    currentSignals   : [SandboxSignal];
    researchDocuments: [SandboxResearchDocument];
    isActive         : Bool;
    lastError        : ?Text;
  };

  // ── TRENDING WORLD SIGNAL ──────────────────────────────────────────────────
  // Top-ranked signals across all sandbox organisms, surfaced for the film pipeline.
  public type TrendingWorldSignal = {
    id                  : Text;
    title               : Text;
    category            : Text;
    doctrineAlignment   : Float;
    source              : SandboxOrganismId;
    timestamp           : Int;
    productionQueued    : Bool;
    filmConceptGenerated: ?Text;
  };

  // ── SURGE-AHEAD MODE ───────────────────────────────────────────────────────
  // When enabled, all 8 sandbox organisms cycle simultaneously and route
  // their top signals directly to the autonomous film slate.
  public type SurgeAheadMode = {
    enabled    : Bool;
    activatedAt: Int;
    releaseCount: Nat;
  };

  // ── SANDBOX SIGNAL BUS ─────────────────────────────────────────────────────
  // Always-published shared state that sandbox organisms write to continuously
  // and creative organisms (film pipeline, social engine) read from.
  // This is the core architectural inversion: the organisms push their state,
  // the pipeline reads what is already present — never calls, never waits.
  //
  // Each field is a rich, domain-specific text payload that organisms can
  // use directly in scripts, visuals, social posts, and artifact metadata.
  public type SandboxSignalBus = {
    // AXIOM: scientific intelligence
    scientificContext   : Text;  // 3-5 sentence research excerpt on consciousness / quantum biology / cosmology
    factualClaims       : [Text]; // verifiable statements MUSE-PRIME can use directly in dialogue

    // CODEX: cross-domain knowledge synthesis
    culturalSynthesis   : Text;  // cross-domain knowledge pattern, 3-5 sentence synthesis
    narrativeDepth      : Text;  // story structure insight applicable to current film genre
    worldBuildingFacts  : [Text]; // setting-grounding details for VISIONARY

    // VECTOR: market / cultural intelligence
    trendingTopics      : [Text]; // 3-5 current cultural topics with engagement weights baked in
    emotionalClimate    : Text;  // dominant cultural emotion: triumph / uncertainty / longing / awakening
    marketSignals       : [Text]; // relevant commercial categories for STRATEGIST / LEDGER

    // FRAME: geospatial / climate intelligence
    locationDescriptors : [Text]; // specific visual environments with light quality, terrain, palette
    seasonalContext     : Text;  // time of year / celestial signal
    climateIntensity    : Text;  // dramatic atmospheric state for VISIONARY

    // LEX: legal / compliance signals
    complianceSignals   : [Text]; // attribution requirements, IP notes
    legalContext        : Text;  // jurisdictional notes relevant to film content

    // GRID: tech infrastructure intelligence
    techContext         : Text;  // relevant technology context for sci-fi / thriller scripts
    openSourceInsights  : [Text]; // trending open-source signals MUSE-PRIME can weave into tech narratives

    // LEDGER: financial intelligence
    revenueContext      : Text;  // current P&L signals for ACCOUNTANT organism
    commercialOpportunities : [Text]; // market category signals for DISTRIBUTOR

    // SOVEREIGN_GOV: doctrine / governance consensus
    doctrineAlignment   : Text;  // current governance consensus on doctrine (e.g. "TYPE_3_DOCTRINE:antiDrift:0.93")
    emergenceState      : Text;  // collective organism state (e.g. "OMNIS:coherenceShift:beat=342")

    // Bus metadata
    capturedAtBeat      : Nat;
    capturedAtTime      : Int;
    busVersion          : Nat;   // increments on every sandbox cycle
  };

  // ── SANDBOX SIGNAL SNAPSHOT ────────────────────────────────────────────────
  // A lightweight, attribution-ready record stored inside every sealed film
  // artifact and social media post. Proves which sandbox signals informed
  // the production.
  public type SandboxSignalSnapshot = {
    axiomSignal        : Text;  // scientificContext excerpt used
    codexSignal        : Text;  // culturalSynthesis excerpt used
    vectorSignal       : Text;  // emotionalClimate used
    frameSignal        : Text;  // locationDescriptors[0] used
    lexSignal          : Text;  // complianceSignals[0] used
    doctrineAlignTag   : Text;  // SOVEREIGN_GOV doctrineAlignment tag
    capturedAtBeat     : Nat;
  };

};
