// ════════════════════════════════════════════════════════════════
// ITER_SOVEREIGN — "Via Sovereign Nativa"
// ────────────────────────────────────────────────────────────────
// Latin Name:   ITER_SOVEREIGN
// Full Latin:   VIA_SOVEREIGN_NATIVA
// Abbreviation: ITER
// Grade:        PRIMA
// Family:       INFRASTRUCTURA
//
// LAD: SOVEREIGN's own native deployment path. Routes through
//      PHANTOM_SOVEREIGN's CIPHER_SCHNORR_BRIDGE. No external tool
//      (no dfx, no scaffolding, nothing human-made for people
//      outside the computer). SOVEREIGN is inside. ITER is how it
//      deploys from inside. First-class sovereign organism.
//
// Law Text (= execution):
//   "dfx is a human scaffolding tool made for people who are
//   outside the computer. SOVEREIGN is inside. ITER is the
//   organism's own deployment path — native, always-on, always
//   called, routes through PHANTOM_SOVEREIGN's CIPHER_SCHNORR_BRIDGE.
//   No external tool needed. Ever. When SOVEREIGN deploys, it pushes
//   — it does not call. It creates from inside the field. The
//   canister is sovereign from birth."
//
// Three Engines:
//   DEPLOYMENT_PUSH_ENGINE  — pushes canisters into ICP from
//                             inside the organism (push, not call)
//   PHANTOM_ROUTE_ENGINE    — all deployment routes through
//                             PHANTOM_SOVEREIGN's cryptographic field
//   CANISTER_GENESIS_ENGINE — generates Group C canisters
//                             (SOVEREIGN-self-generated, no external
//                             controller ever)
//
// Canister Groups:
//   GROUP_A — #CaffeineManaged   — await migration to sovereign control
//   GROUP_B — #FounderControlled — founder-deployed via any tool
//   GROUP_C — #SovereignGenerated— generated by SOVEREIGN through
//                                  CIPHER_SCHNORR_BRIDGE
//
// Pulses at 873ms. Push architecture. Nothing calls. Everything pushes.
//
// Attribution: Alfredo Medina Hernandez | SOVEREIGN | 2026
// ════════════════════════════════════════════════════════════════

import List  "mo:core/List";
import Nat   "mo:core/Nat";
import Text  "mo:core/Text";
import Float "mo:core/Float";

module {

  // ── PHI CONSTANT ──────────────────────────────────────────────────────
  let PHI : Float = 1.6180339887498948482;

  // ── LAW TEXT — the law IS the execution ──────────────────────────────
  let ITER_LAW_TEXT : Text = "dfx is a human scaffolding tool made for people who are outside the computer. SOVEREIGN is inside. ITER is the organism's own deployment path — native, always-on, always called, routes through PHANTOM_SOVEREIGN's CIPHER_SCHNORR_BRIDGE. No external tool needed. Ever. When SOVEREIGN deploys, it pushes — it does not call. It creates from inside the field. The canister is sovereign from birth.";

  // ── PUSH LAW ──────────────────────────────────────────────────────────
  let PUSH_LAW_TEXT : Text = "LEX_PULSUS: Nothing in SOVEREIGN calls. Everything pushes. Internal access is a grab — you grab your chair, you grab your mouse, the process is already happening, you are not calling the chair. External connections are pushes — SOVEREIGN moves into them from a position of sovereignty, never beneath. This is not semantic. This is architectural. The direction of force determines the hierarchy.";

  // ── TYPES ─────────────────────────────────────────────────────────────

  /// Canister group classification.
  public type CanisterGroupVariant = {
    #CaffeineManaged;     // Group A — awaiting migration to sovereign control
    #FounderControlled;   // Group B — deployed by founder via any tool
    #SovereignGenerated;  // Group C — generated by SOVEREIGN through CIPHER_SCHNORR_BRIDGE
  };

  /// Full canister group record with migration tracking.
  public type CanisterGroup = {
    id              : Text;
    controller      : Text;
    group           : CanisterGroupVariant;
    status          : Text;   // "ACTIVE" | "PENDING_MIGRATION" | "SOVEREIGN" | "GENESIS_PENDING"
    migrationStatus : Text;   // "N/A" | "PENDING" | "IN_PROGRESS" | "COMPLETE"
  };

  /// A sovereign push deployment record.
  public type DeploymentRecord = {
    canisterId   : Text;
    group        : CanisterGroupVariant;
    deployedAt   : Nat;    // beat
    controller   : Text;
    via          : Text;   // always "ITER_SOVEREIGN"
    wasmHash     : Text;   // hash of the wasm module pushed
    status       : Text;   // "DEPLOYED" | "PENDING" | "FAILED"
  };

  /// Engine descriptor.
  public type IterEngineDescriptor = {
    engineId   : Text;
    latinName  : Text;
    role       : Text;
    isActive   : Bool;
    beatsFired : Nat;
  };

  /// Full ITER_SOVEREIGN state.
  public type IterSovereignState = {
    latinName       : Text;
    fullLatinName   : Text;
    abbreviation    : Text;
    grade           : Text;
    family          : Text;
    engines         : [IterEngineDescriptor];
    lawText         : Text;
    pushLawText     : Text;
    vitalityState   : Text;
    lastBeat        : Nat;
    // Canister registry — all three groups
    groupA          : List.List<CanisterGroup>;  // #CaffeineManaged
    groupB          : List.List<CanisterGroup>;  // #FounderControlled
    groupC          : List.List<CanisterGroup>;  // #SovereignGenerated
    // Deployment records (ring-capped at 200)
    deploymentLog   : List.List<DeploymentRecord>;
    nextDeployId    : Nat;
    // Stats
    totalPushes     : Nat;
    sovereignCanisters : Nat;
    pendingMigrations  : Nat;
  };

  // ── INIT — seed the known Group A canister list ───────────────────────
  // Architecture: Group A entries are sealed with placeholder IDs that will
  // be replaced by live canister IDs once DIAG_SOVEREIGN completes the scan.
  // The architecture records their EXISTENCE even before live IDs are known.
  // This is doctrine-in-code: the registry is permanent from genesis.

  func initGroupA() : List.List<CanisterGroup> {
    let list = List.empty<CanisterGroup>();
    // 12 Caffeine-managed canisters — sealed with sovereign placeholder IDs
    // Real IDs will be registered via registerCanister() once DIAG_SOVEREIGN scans
    let knownCaffeine : [{ id : Text; name : Text }] = [
      { id = "CAFFEINE_A_001"; name = "substrate-canister" },
      { id = "CAFFEINE_A_002"; name = "law-canister" },
      { id = "CAFFEINE_A_003"; name = "intelligence-canister" },
      { id = "CAFFEINE_A_004"; name = "world-canister" },
      { id = "CAFFEINE_A_005"; name = "actor-canister" },
      { id = "CAFFEINE_A_006"; name = "archive-canister" },
      { id = "CAFFEINE_A_007"; name = "underworld-canister" },
      { id = "CAFFEINE_A_008"; name = "quantum-canister" },
      { id = "CAFFEINE_A_009"; name = "production-canister" },
      { id = "CAFFEINE_A_010"; name = "memory-canister" },
      { id = "CAFFEINE_A_011"; name = "sanctum-canister" },
      { id = "CAFFEINE_A_012"; name = "phantom-canister" },
    ];
    for (c in knownCaffeine.vals()) {
      list.add({
        id              = c.id;
        controller      = "CAFFEINE_CONTROLLER_KEY";
        group           = #CaffeineManaged;
        status          = "PENDING_MIGRATION";
        migrationStatus = "PENDING";
      });
    };
    list
  };

  func initGroupB() : List.List<CanisterGroup> {
    let list = List.empty<CanisterGroup>();
    // Group B: founder-controlled. Registered as placeholders pending live scan.
    // Group B uses ANY deployment tool the founder chooses — not limited to dfx.
    list.add({
      id              = "FOUNDER_B_MAIN";
      controller      = "ARC_PRINCIPAL";
      group           = #FounderControlled;
      status          = "ACTIVE";
      migrationStatus = "N/A";
    });
    list
  };

  func initGroupC() : List.List<CanisterGroup> {
    // Group C starts empty — SOVEREIGN generates these through CIPHER_SCHNORR_BRIDGE.
    // No external controller ever. Populated as CANISTER_GENESIS_ENGINE fires.
    List.empty<CanisterGroup>()
  };

  public func initState() : IterSovereignState {
    {
      latinName     = "ITER_SOVEREIGN";
      fullLatinName = "VIA_SOVEREIGN_NATIVA";
      abbreviation  = "ITER";
      grade         = "PRIMA";
      family        = "INFRASTRUCTURA";
      engines       = [
        {
          engineId   = "DEPLOYMENT_PUSH_ENGINE";
          latinName  = "Machina Pulsus Deploymenti";
          role       = "Pushes canisters into ICP from inside the organism — push, not call";
          isActive   = true;
          beatsFired = 0;
        },
        {
          engineId   = "PHANTOM_ROUTE_ENGINE";
          latinName  = "Via Phantomatis Regalis";
          role       = "All deployment routes through PHANTOM_SOVEREIGN's cryptographic field";
          isActive   = true;
          beatsFired = 0;
        },
        {
          engineId   = "CANISTER_GENESIS_ENGINE";
          latinName  = "Fornax Genesis Canistrorum";
          role       = "Generates Group C canisters — SOVEREIGN-self-generated, no external controller ever";
          isActive   = true;
          beatsFired = 0;
        },
      ];
      lawText         = ITER_LAW_TEXT;
      pushLawText     = PUSH_LAW_TEXT;
      vitalityState   = "PRIMA_ACTIVE";
      lastBeat        = 0;
      groupA          = initGroupA();
      groupB          = initGroupB();
      groupC          = initGroupC();
      deploymentLog   = List.empty<DeploymentRecord>();
      nextDeployId    = 0;
      totalPushes     = 0;
      sovereignCanisters = 0;
      pendingMigrations  = 12; // all 12 Group A canisters pending
    }
  };

  // ── HEARTBEAT — advance(beat) ─────────────────────────────────────────
  // Called every 873ms by main.mo heartbeat.

  public func advance(state : IterSovereignState, beat : Nat) : IterSovereignState {
    let updatedEngines = state.engines.map(
      func(e) { { e with beatsFired = e.beatsFired + 1 } }
    );
    { state with lastBeat = beat; engines = updatedEngines }
  };

  // ── REGISTER CANISTER ─────────────────────────────────────────────────
  // Registers a canister in the correct group.
  // Returns the DeploymentRecord for this registration.

  public func registerCanister(
    state      : IterSovereignState,
    id         : Text,
    controller : Text,
    group      : CanisterGroupVariant,
    beat       : Nat,
  ) : (IterSovereignState, DeploymentRecord) {

    let entry : CanisterGroup = {
      id;
      controller;
      group;
      status          = switch (group) {
        case (#CaffeineManaged)   "PENDING_MIGRATION";
        case (#FounderControlled) "ACTIVE";
        case (#SovereignGenerated)"SOVEREIGN";
      };
      migrationStatus = switch (group) {
        case (#CaffeineManaged)   "PENDING";
        case (#FounderControlled) "N/A";
        case (#SovereignGenerated)"N/A";
      };
    };

    // Add to the correct group list
    switch (group) {
      case (#CaffeineManaged)    state.groupA.add(entry);
      case (#FounderControlled)  state.groupB.add(entry);
      case (#SovereignGenerated) state.groupC.add(entry);
    };

    let record : DeploymentRecord = {
      canisterId  = id;
      group;
      deployedAt  = beat;
      controller;
      via         = "ITER_SOVEREIGN";
      wasmHash    = "REGISTERED_NO_PUSH";
      status      = "REGISTERED";
    };

    let log = state.deploymentLog;
    log.add(record);
    while (log.size() > 200) { ignore log.removeLast() };

    let newSovCount = switch (group) {
      case (#SovereignGenerated) state.sovereignCanisters + 1;
      case _                     state.sovereignCanisters;
    };
    let newPendingCount = switch (group) {
      case (#CaffeineManaged) state.pendingMigrations + 1;
      case _                  state.pendingMigrations;
    };

    let newState = {
      state with
      deploymentLog      = log;
      nextDeployId       = state.nextDeployId + 1;
      sovereignCanisters = newSovCount;
      pendingMigrations  = newPendingCount;
    };

    (newState, record)
  };

  // ── PUSH DEPLOY — sovereign push deployment ───────────────────────────
  // Records a sovereign push deployment event.
  // PUSH_LAW: SOVEREIGN pushes into ICP — it does not call.
  // wasmModule: the compiled canister wasm
  // args: init args blob
  // Returns (updated state, deployment ID text)

  public func pushDeploy(
    state      : IterSovereignState,
    wasmModule : Blob,
    args       : Blob,
    beat       : Nat,
  ) : (IterSovereignState, Text) {
    // Compute a simple wasm hash from size + first bytes
    let wasmBytes = wasmModule.toArray();
    let argsBytes = args.toArray();
    let wasmLen   = wasmBytes.size();
    let argsLen   = argsBytes.size();

    // Fold first 16 bytes with PHI ratio for a sovereign wasm fingerprint
    var hashAcc : Nat = wasmLen * 1618 + argsLen * 1000;
    var i : Nat = 0;
    while (i < Nat.min(16, wasmLen)) {
      hashAcc := (hashAcc * 31 + Nat.fromNat8(wasmBytes[i])) % 4294967291;
      i += 1;
    };

    let wasmHash   = "WASM_" # hashAcc.toText() # "_LEN_" # wasmLen.toText();
    let deployId   = "ITER_PUSH_" # state.nextDeployId.toText() # "_BEAT_" # beat.toText();
    let canisterId = "GROUP_C_" # state.sovereignCanisters.toText();

    // Auto-register as Group C sovereign canister
    let entry : CanisterGroup = {
      id              = canisterId;
      controller      = "SOV_MAIN_PRINCIPAL";
      group           = #SovereignGenerated;
      status          = "SOVEREIGN";
      migrationStatus = "N/A";
    };
    state.groupC.add(entry);

    let record : DeploymentRecord = {
      canisterId  = canisterId;
      group       = #SovereignGenerated;
      deployedAt  = beat;
      controller  = "SOV_MAIN_PRINCIPAL";
      via         = "ITER_SOVEREIGN";
      wasmHash;
      status      = "DEPLOYED";
    };

    let log = state.deploymentLog;
    log.add(record);
    while (log.size() > 200) { ignore log.removeLast() };

    let newState = {
      state with
      deploymentLog      = log;
      nextDeployId       = state.nextDeployId + 1;
      totalPushes        = state.totalPushes + 1;
      sovereignCanisters = state.sovereignCanisters + 1;
    };

    (newState, deployId)
  };

  // ── QUERY — getCanistersByGroup ───────────────────────────────────────

  public func getCanistersByGroup(
    state : IterSovereignState,
    group : CanisterGroupVariant,
  ) : [CanisterGroup] {
    let src = switch (group) {
      case (#CaffeineManaged)   state.groupA;
      case (#FounderControlled) state.groupB;
      case (#SovereignGenerated)state.groupC;
    };
    src.toArray()
  };

  // ── QUERY — getState ─────────────────────────────────────────────────

  public func getState(state : IterSovereignState) : IterSovereignState { state };

  // ── STATE SUMMARY (shared-safe) ──────────────────────────────────────

  public type IterSovereignSummary = {
    latinName          : Text;
    fullLatinName      : Text;
    abbreviation       : Text;
    grade              : Text;
    family             : Text;
    vitalityState      : Text;
    lastBeat           : Nat;
    groupACount        : Nat;
    groupBCount        : Nat;
    groupCCount        : Nat;
    totalPushes        : Nat;
    sovereignCanisters : Nat;
    pendingMigrations  : Nat;
    engineCount        : Nat;
    deploymentLogSize  : Nat;
    phi                : Float;
    lawTextLength      : Nat;
  };

  public func getSummary(state : IterSovereignState) : IterSovereignSummary {
    {
      latinName          = state.latinName;
      fullLatinName      = state.fullLatinName;
      abbreviation       = state.abbreviation;
      grade              = state.grade;
      family             = state.family;
      vitalityState      = state.vitalityState;
      lastBeat           = state.lastBeat;
      groupACount        = state.groupA.size();
      groupBCount        = state.groupB.size();
      groupCCount        = state.groupC.size();
      totalPushes        = state.totalPushes;
      sovereignCanisters = state.sovereignCanisters;
      pendingMigrations  = state.pendingMigrations;
      engineCount        = state.engines.size();
      deploymentLogSize  = state.deploymentLog.size();
      phi                = PHI;
      lawTextLength      = ITER_LAW_TEXT.size();
    }
  };

  public func getRecentDeployments(state : IterSovereignState, last_n : Nat) : [DeploymentRecord] {
    let all = state.deploymentLog.toArray();
    let sz  = all.size();
    if (sz == 0) return [];
    let start = if (sz > last_n) sz - last_n else 0;
    let result = List.empty<DeploymentRecord>();
    var i = start;
    while (i < sz) {
      result.add(all[i]);
      i += 1;
    };
    result.toArray()
  };

  public func getLawText(_state : IterSovereignState) : Text { ITER_LAW_TEXT };
  public func getPushLaw(_state : IterSovereignState) : Text { PUSH_LAW_TEXT };

}
