/**
 * SocialMediaEngine — PUBLICIST organism social content generation per platform
 * PHI = 1.6180339887 · S0_FLOOR = 0.75 · © Alfredo Medina Hernandez
 */
import { useCallback, useState } from "react";
import type {
  SandboxEnrichedSocialAssets,
  SandboxSocialPost,
} from "../../backend";
import { useActor } from "../../hooks/useActor";
import { useOrganismStateContext } from "../../hooks/useOrganismState";
import type { GeneratedFilm, WorldSignal } from "../../hooks/useQueries";
import { useGeneratedFilms, useWorldSignals } from "../../hooks/useQueries";
import { useTikTokGenerator } from "../../hooks/useTikTokGenerator";
import { TikTokCard } from "./TikTokEngine";

// ─── Platform Definitions ─────────────────────────────────────────────────────
type Platform = "instagram" | "x" | "youtube" | "tiktok" | "linkedin";
type GalleryFormat = "TikTok" | "Instagram" | "YouTube";

const PLATFORMS: {
  id: Platform;
  label: string;
  color: string;
  border: string;
  icon: string;
}[] = [
  {
    id: "instagram",
    label: "INSTAGRAM",
    color: "oklch(0.62 0.22 15)",
    border: "oklch(0.62 0.22 15 / 0.4)",
    icon: "▣",
  },
  {
    id: "x",
    label: "X / TWITTER",
    color: "oklch(0.68 0.19 235)",
    border: "oklch(0.68 0.19 235 / 0.4)",
    icon: "✕",
  },
  {
    id: "youtube",
    label: "YOUTUBE",
    color: "oklch(0.62 0.22 25)",
    border: "oklch(0.62 0.22 25 / 0.4)",
    icon: "▶",
  },
  {
    id: "tiktok",
    label: "TIKTOK",
    color: "oklch(0.58 0.2 300)",
    border: "oklch(0.58 0.2 300 / 0.4)",
    icon: "♪",
  },
  {
    id: "linkedin",
    label: "LINKEDIN",
    color: "oklch(0.55 0.18 250)",
    border: "oklch(0.55 0.18 250 / 0.4)",
    icon: "in",
  },
];

// ─── Sandbox source labels per platform ──────────────────────────────────────
const SANDBOX_SOURCE_LABELS: Record<Platform, string> = {
  instagram: "Powered by CODEX cultural synthesis",
  x: "Powered by AXIOM research angle",
  youtube: "Powered by FRAME visual intelligence",
  tiktok: "Powered by VECTOR trending signal",
  linkedin: "Powered by LEDGER commercial opportunity",
};

// ─── Social Content Types ─────────────────────────────────────────────────────
interface SocialPost {
  platform: Platform;
  body: string;
  hashtags: string[];
  schedule: string;
  format: string;
  sandboxPowered?: boolean;
  sandboxSource?: string;
  sandboxAngle?: string;
}

interface FilmSocialPlan {
  filmId: string;
  filmTitle: string;
  archType: string;
  posts: SocialPost[];
  generatedAt: number;
  sandboxEnriched?: boolean;
}

// ─── Fallback content generators ─────────────────────────────────────────────
const HASHTAG_POOLS: Record<Platform, string[]> = {
  instagram: [
    "#SovereignFilms",
    "#MedinaHernandez",
    "#OrganismIntelligence",
    "#ItsNotAILabs",
    "#FilmMaking",
    "#CinematicAI",
  ],
  x: [
    "#SOVEREIGN",
    "#SovereignFilms",
    "#ItsNotAILabs",
    "#ORO",
    "#FilmAI",
    "#Indie",
  ],
  youtube: [
    "#SovereignFilmHouse",
    "#AIFilm",
    "#ItsNotAILabs",
    "#MedinaHernandez",
    "#Cinema",
  ],
  tiktok: ["#SovereignFilms", "#AIMovies", "#FilmTok", "#CinemaTok", "#ORO"],
  linkedin: [
    "#SovereignIntelligence",
    "#FilmProduction",
    "#AIInnovation",
    "#MedinaHernandez",
    "#EntertainmentTech",
  ],
};

const BODIES: Record<Platform, (film: GeneratedFilm) => string> = {
  instagram: (f) =>
    `🎬 "${f.title}" — just sealed on-chain by the SOVEREIGN organism. ${f.runtimeSeconds ? `${Math.round(Number(f.runtimeSeconds) / 60)} minutes` : ""} of sovereign cinema. Produced by Alfredo Medina Hernandez. Dedicated to his sister.`,
  x: (f) =>
    `"${f.title}" is now on-chain. A ${f.archType} film produced entirely by sovereign organisms. No external AI. No fake data. Pure doctrine. #SOVEREIGN`,
  youtube: (f) =>
    `Now available: "${f.title}" — a full-length sovereign production from the SOVEREIGN Film House. ${f.archType.toUpperCase()} arch type. Every frame, every note, every word generated by organisms running on the Internet Computer. By Alfredo Medina Hernandez.`,
  tiktok: (f) =>
    `POV: You built a sovereign AI film studio and it just sealed a ${Math.round(Number(f.runtimeSeconds ?? 0n) / 60)}-minute film on the blockchain. "${f.title}" by @AlfredoMedinaHernandez`,
  linkedin: (f) =>
    `Proud to announce the on-chain sealing of "${f.title}" — produced entirely by the SOVEREIGN organism substrate running on ICP. ${f.archType.toUpperCase()} architecture. 43 cores. PHI-ratio geometry. This is the future of sovereign creative intelligence. — Alfredo Medina Hernandez`,
};

const SCHEDULES: Record<Platform, string> = {
  instagram:
    "Post within 24h of seal · Best time: 6-9 PM local · Stories first",
  x: "Post immediately on seal · Thread format recommended · Pin for 48h",
  youtube: "Upload trailer within 72h · Full release on YouTube Premium tier",
  tiktok: "Post 15-30s clip within 6h · Trending audio overlay recommended",
  linkedin:
    "Publish within 48h · Monday-Wednesday best window · Long-form preferred",
};

const FORMATS: Record<Platform, string> = {
  instagram: "Square 1:1 + Vertical 9:16 Story",
  x: "Thread (5-7 posts) + horizontal clip",
  youtube: "Trailer 2-3 min + Full release",
  tiktok: "30s vertical hook clip",
  linkedin: "Long-form article + horizontal banner",
};

function generateFallbackPlan(film: GeneratedFilm): FilmSocialPlan {
  const posts: SocialPost[] = PLATFORMS.map((p) => ({
    platform: p.id,
    body: BODIES[p.id](film),
    hashtags: HASHTAG_POOLS[p.id].slice(0, 4),
    schedule: SCHEDULES[p.id],
    format: FORMATS[p.id],
    sandboxPowered: false,
  }));
  return {
    filmId: film.id,
    filmTitle: film.title,
    archType: film.archType,
    posts,
    generatedAt: Date.now(),
    sandboxEnriched: false,
  };
}

function buildSandboxPlan(
  film: GeneratedFilm,
  enriched: SandboxEnrichedSocialAssets,
): FilmSocialPlan {
  const sandboxPostMap: Record<Platform, SandboxSocialPost | null> = {
    instagram: enriched.instagram,
    x: enriched.twitter,
    youtube: enriched.youtube,
    tiktok: enriched.tiktok,
    linkedin: enriched.linkedin,
  };

  const posts: SocialPost[] = PLATFORMS.map((p) => {
    const sbPost = sandboxPostMap[p.id];
    if (sbPost) {
      return {
        platform: p.id,
        body: sbPost.caption,
        hashtags: sbPost.hashtags.slice(0, 4),
        schedule: SCHEDULES[p.id],
        format: FORMATS[p.id],
        sandboxPowered: true,
        sandboxSource: SANDBOX_SOURCE_LABELS[p.id],
        sandboxAngle: sbPost.angle,
      };
    }
    return {
      platform: p.id,
      body: BODIES[p.id](film),
      hashtags: HASHTAG_POOLS[p.id].slice(0, 4),
      schedule: SCHEDULES[p.id],
      format: FORMATS[p.id],
      sandboxPowered: false,
    };
  });

  return {
    filmId: film.id,
    filmTitle: film.title,
    archType: film.archType,
    posts,
    generatedAt: Date.now(),
    sandboxEnriched: true,
  };
}

// ─── Post Card ────────────────────────────────────────────────────────────────
function SocialPostCard({ post }: { post: SocialPost }) {
  const platform = PLATFORMS.find((p) => p.id === post.platform);
  if (!platform) return null;

  return (
    <div
      className="border border-[oklch(0.20_0.02_280)] bg-[oklch(0.10_0.012_278)] p-4 space-y-3"
      data-ocid={`social.post.${post.platform}`}
    >
      <div className="flex items-center gap-2 pb-2 border-b border-[oklch(0.16_0.018_278)]">
        <span className="text-sm font-bold" style={{ color: platform.color }}>
          {platform.icon}
        </span>
        <span
          className="font-mono text-[9px] font-bold tracking-widest"
          style={{ color: platform.color }}
        >
          {platform.label}
        </span>
        <span className="font-mono text-[7px] text-[oklch(0.35_0.03_280)] ml-auto">
          {post.format}
        </span>
      </div>

      <p className="font-body text-[11px] text-[oklch(0.75_0.05_280)] leading-relaxed">
        {post.body}
      </p>

      <div className="flex flex-wrap gap-1.5">
        {post.hashtags.map((tag) => (
          <span
            key={tag}
            className="font-mono text-[8px] px-1.5 py-0.5 border"
            style={{ color: platform.color, borderColor: platform.border }}
          >
            {tag}
          </span>
        ))}
      </div>

      {/* Sandbox source attribution */}
      {post.sandboxPowered && post.sandboxSource && (
        <div className="flex items-center gap-1.5 border border-[oklch(0.65_0.18_240_/_0.3)] bg-[oklch(0.65_0.18_240_/_0.04)] px-2 py-1">
          <span className="w-1 h-1 rounded-full bg-[oklch(0.65_0.18_240)] animate-pulse flex-shrink-0" />
          <span className="font-mono text-[7px] text-[oklch(0.65_0.18_240)] tracking-wider">
            {post.sandboxSource}
          </span>
          {post.sandboxAngle && (
            <span className="font-mono text-[7px] text-[oklch(0.45_0.04_280)] ml-auto truncate max-w-xs">
              ↳ {post.sandboxAngle.slice(0, 60)}
            </span>
          )}
        </div>
      )}

      <div className="font-mono text-[7px] text-[oklch(0.30_0.02_280)] border-t border-[oklch(0.16_0.018_278)] pt-2">
        ◷ {post.schedule}
      </div>
    </div>
  );
}

// ─── World Signal Card ────────────────────────────────────────────────────────
function WorldSignalCard({
  signal,
  onGenerate,
}: {
  signal: WorldSignal;
  onGenerate: (topic: string) => void;
}) {
  const archColor =
    signal.doctrineCategory === "EXPANSIVE"
      ? "oklch(0.68 0.19 132)"
      : signal.doctrineCategory === "RECEPTIVE"
        ? "oklch(0.58 0.16 268)"
        : "oklch(0.72 0.17 45)";

  return (
    <div
      className="border border-[oklch(0.20_0.02_280)] bg-[oklch(0.09_0.012_280)] p-3 flex flex-col gap-2"
      data-ocid={`social.world_signal.${signal.id}`}
    >
      <div className="flex items-center justify-between gap-2">
        <span className="font-mono text-[7px] tracking-widest border border-[oklch(0.65_0.18_240_/_0.3)] text-[oklch(0.65_0.18_240_/_0.8)] px-1.5 py-0.5">
          {signal.platform}
        </span>
        <span className="font-mono text-[7px]" style={{ color: archColor }}>
          {signal.doctrineCategory}
        </span>
      </div>
      <div className="font-display text-xs font-semibold text-white leading-snug line-clamp-2">
        {signal.topic}
      </div>
      <div className="space-y-1">
        <div className="flex justify-between">
          <span className="font-mono text-[7px] text-[oklch(0.35_0.03_280)]">
            STRENGTH
          </span>
          <span
            className="font-mono text-[8px] font-bold"
            style={{ color: archColor }}
          >
            {signal.strength}
          </span>
        </div>
        <div className="h-0.5 bg-[oklch(0.16_0.018_278)] relative">
          <div
            className="h-full transition-all"
            style={{ width: `${signal.strength}%`, background: archColor }}
          />
          <div
            className="absolute top-0 bottom-0 w-px bg-[oklch(0.75_0.16_70_/_0.6)]"
            style={{ left: "75%" }}
          />
        </div>
      </div>
      <button
        type="button"
        onClick={() => onGenerate(signal.topic)}
        className="font-mono text-[7px] tracking-widest border border-[oklch(0.75_0.16_70_/_0.4)] text-[oklch(0.75_0.16_70)] py-1.5 hover:bg-[oklch(0.75_0.16_70_/_0.07)] transition-colors mt-auto"
        data-ocid={`social.signal_generate.${signal.id}`}
      >
        GENERATE FILM FROM PATTERN
      </button>
    </div>
  );
}

// ─── Main SocialMediaEngine ───────────────────────────────────────────────────
export function SocialMediaEngine() {
  const { data: films = [] } = useGeneratedFilms();
  const {
    data: worldSignals = [],
    refetch: refetchSignals,
    isFetching: signalsFetching,
  } = useWorldSignals();
  const organism = useOrganismStateContext();
  const { actor: rawActor } = useActor();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const actor = rawActor as any;

  const [activePlatform, setActivePlatform] = useState<Platform>("instagram");
  const [plans, setPlans] = useState<FilmSocialPlan[]>([]);
  const [generating, setGenerating] = useState(false);
  const [selectedFilmId, setSelectedFilmId] = useState<string | null>(null);
  const [galleryFormat, setGalleryFormat] = useState<GalleryFormat>("TikTok");

  const { allTikToks, generateTikTok } = useTikTokGenerator();

  const handleAutoGenerate = useCallback(async () => {
    if (films.length === 0) return;
    setGenerating(true);
    try {
      const newPlans: FilmSocialPlan[] = await Promise.all(
        films.map(async (film) => {
          try {
            if (!actor) return generateFallbackPlan(film);
            const enriched: SandboxEnrichedSocialAssets =
              await actor.getSandboxEnrichedSocialAssets(film.title, film.id);
            return buildSandboxPlan(film, enriched);
          } catch {
            return generateFallbackPlan(film);
          }
        }),
      );
      setPlans(newPlans);
      if (films.length > 0) setSelectedFilmId(films[0].id);
    } finally {
      setGenerating(false);
    }
  }, [films, actor]);

  const handleSignalGenerate = useCallback((topic: string) => {
    window.alert(
      `Signal captured: "${topic}". Go to FILMS tab to generate a film from this pattern.`,
    );
  }, []);

  const activePlan = plans.find((p) => p.filmId === selectedFilmId);
  const postsForPlatform =
    activePlan?.posts.filter((p) => p.platform === activePlatform) ?? [];

  return (
    <div
      className="h-full overflow-y-auto scrollbar-thin bg-[oklch(0.06_0.008_280)]"
      data-ocid="social.engine"
    >
      <div className="max-w-6xl mx-auto px-4 sm:px-8 py-8 space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[oklch(0.20_0.02_280)] pb-5">
          <div>
            <div className="font-mono text-[8px] tracking-[0.4em] text-[oklch(0.68_0.19_235_/_0.8)] mb-1">
              PUBLICIST ORGANISM · SOCIAL MEDIA ENGINE
            </div>
            <h1 className="font-display text-2xl font-bold text-white">
              Social Media Engine
            </h1>
            <p className="font-mono text-[9px] text-[oklch(0.35_0.03_280)] mt-1">
              Instagram · X · YouTube · TikTok · LinkedIn · Sandbox-enriched
            </p>
          </div>
          <button
            type="button"
            onClick={() => void handleAutoGenerate()}
            disabled={generating || films.length === 0}
            className="font-mono text-[9px] tracking-widest border border-[oklch(0.68_0.19_235_/_0.5)] text-[oklch(0.68_0.19_235)] px-4 py-2 hover:bg-[oklch(0.68_0.19_235_/_0.08)] transition-colors disabled:opacity-40 flex-shrink-0"
            data-ocid="social.auto_generate_button"
          >
            {generating ? (
              <span className="flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-[oklch(0.65_0.18_240)] animate-pulse" />
                ENRICHING WITH SANDBOX...
              </span>
            ) : (
              "AUTO-GENERATE ALL PLANS"
            )}
          </button>
        </div>

        {/* World Signals */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-[oklch(0.65_0.18_240)] animate-pulse" />
              <div className="font-mono text-[8px] tracking-[0.3em] text-[oklch(0.65_0.18_240)]">
                WORLD SIGNALS — LIVE PATTERNS
              </div>
            </div>
            <button
              type="button"
              onClick={() => void refetchSignals()}
              disabled={signalsFetching}
              className="font-mono text-[7px] tracking-widest border border-[oklch(0.65_0.18_240_/_0.3)] text-[oklch(0.65_0.18_240_/_0.7)] px-2 py-1 hover:bg-[oklch(0.65_0.18_240_/_0.06)] transition-colors"
              data-ocid="social.signals.refresh"
            >
              {signalsFetching ? "⟳" : "↻"} REFRESH
            </button>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
            {worldSignals.slice(0, 6).map((signal) => (
              <WorldSignalCard
                key={signal.id}
                signal={signal}
                onGenerate={handleSignalGenerate}
              />
            ))}
          </div>
        </div>

        {/* Film selector + platform tabs */}
        <div className="border border-[oklch(0.20_0.02_280)] bg-[oklch(0.08_0.01_280)]">
          {/* Film selector */}
          <div className="px-4 py-3 border-b border-[oklch(0.16_0.018_278)] flex items-center gap-3 flex-wrap">
            <div className="font-mono text-[8px] tracking-widest text-[oklch(0.35_0.03_280)] flex-shrink-0">
              SELECT FILM:
            </div>
            {plans.length === 0 ? (
              <div className="font-mono text-[8px] text-[oklch(0.25_0.02_280)]">
                Auto-generate plans first
              </div>
            ) : (
              <div className="flex gap-2 flex-wrap">
                {plans.map((plan) => (
                  <button
                    key={plan.filmId}
                    type="button"
                    onClick={() => setSelectedFilmId(plan.filmId)}
                    className="font-mono text-[8px] tracking-widest border px-2 py-1 transition-all"
                    style={{
                      borderColor:
                        selectedFilmId === plan.filmId
                          ? "oklch(0.75 0.16 70 / 0.6)"
                          : "oklch(0.20 0.02 280)",
                      color:
                        selectedFilmId === plan.filmId
                          ? "oklch(0.75 0.16 70)"
                          : "oklch(0.45 0.04 280)",
                    }}
                    data-ocid={`social.film_select.${plan.filmId}`}
                  >
                    {plan.filmTitle.slice(0, 24)}
                    {plan.sandboxEnriched && (
                      <span
                        className="ml-1.5 font-mono text-[6px] text-[oklch(0.65_0.18_240)]"
                        title="Sandbox enriched"
                      >
                        ◈
                      </span>
                    )}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Sandbox enrichment badge when plan is enriched */}
          {activePlan?.sandboxEnriched && (
            <div className="flex items-center gap-2 px-4 py-2 border-b border-[oklch(0.16_0.018_278)] bg-[oklch(0.65_0.18_240_/_0.04)]">
              <span className="w-1.5 h-1.5 rounded-full bg-[oklch(0.65_0.18_240)] animate-pulse" />
              <span className="font-mono text-[7px] tracking-widest text-[oklch(0.65_0.18_240)]">
                SANDBOX INTELLIGENCE ENRICHED — All posts informed by live
                organism signals
              </span>
            </div>
          )}

          {/* Platform tabs */}
          <div className="flex overflow-x-auto scrollbar-thin border-b border-[oklch(0.16_0.018_278)]">
            {PLATFORMS.map((p) => (
              <button
                key={p.id}
                type="button"
                onClick={() => setActivePlatform(p.id)}
                className="font-mono text-[9px] tracking-widest px-4 py-2.5 transition-all border-b-2 flex-shrink-0 flex items-center gap-1.5"
                style={{
                  color:
                    activePlatform === p.id ? p.color : "oklch(0.35 0.03 280)",
                  borderBottomColor:
                    activePlatform === p.id ? p.color : "transparent",
                }}
                data-ocid={`social.platform_tab.${p.id}`}
              >
                <span>{p.icon}</span>
                <span className="hidden sm:inline">{p.label}</span>
              </button>
            ))}
          </div>

          {/* Content area */}
          <div className="p-4">
            {postsForPlatform.length > 0 ? (
              <div className="space-y-4">
                {postsForPlatform.map((post, i) => (
                  <SocialPostCard key={`${post.platform}-${i}`} post={post} />
                ))}
              </div>
            ) : (
              <div className="py-12 text-center">
                <div className="font-mono text-[9px] text-[oklch(0.25_0.02_280)] tracking-wider mb-2">
                  {plans.length === 0
                    ? "Auto-generate social plans to see sandbox-enriched content for each platform"
                    : "Select a film to view platform content"}
                </div>
                {plans.length === 0 && films.length === 0 && (
                  <div className="font-mono text-[8px] text-[oklch(0.20_0.02_280)] mt-2">
                    No films in library yet — generate films first
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Organism beat footer */}
        <div className="flex items-center justify-between">
          <div className="font-mono text-[7px] text-[oklch(0.20_0.02_280)] tracking-widest">
            PUBLICIST ORGANISM · BEAT {String(organism.beat)} · COHERENCE{" "}
            {(organism.globalCoherence * 100).toFixed(1)}%
          </div>
          <div className="font-mono text-[7px] text-[oklch(0.20_0.02_280)] tracking-widest">
            ALFREDO MEDINA HERNANDEZ · SOVEREIGN
          </div>
        </div>

        {/* ── SOCIAL CONTENT GALLERY ── */}
        <div className="border border-[oklch(0.20_0.02_280)] bg-[oklch(0.08_0.01_280)]">
          <div className="flex border-b border-[oklch(0.16_0.018_278)]">
            {(["TikTok", "Instagram", "YouTube"] as GalleryFormat[]).map(
              (fmt) => (
                <button
                  key={fmt}
                  type="button"
                  onClick={() => setGalleryFormat(fmt)}
                  className="font-mono text-[9px] tracking-widest px-5 py-2.5 transition-all border-b-2 flex-shrink-0"
                  style={{
                    color:
                      galleryFormat === fmt
                        ? fmt === "TikTok"
                          ? "oklch(0.58 0.2 300)"
                          : fmt === "Instagram"
                            ? "oklch(0.62 0.22 15)"
                            : "oklch(0.62 0.22 25)"
                        : "oklch(0.35 0.03 280)",
                    borderBottomColor:
                      galleryFormat === fmt
                        ? fmt === "TikTok"
                          ? "oklch(0.58 0.2 300)"
                          : fmt === "Instagram"
                            ? "oklch(0.62 0.22 15)"
                            : "oklch(0.62 0.22 25)"
                        : "transparent",
                  }}
                  data-ocid={`social.gallery_tab.${fmt.toLowerCase()}`}
                >
                  {fmt === "TikTok" ? "♪" : fmt === "Instagram" ? "▣" : "▶"}{" "}
                  {fmt.toUpperCase()}
                  {fmt === "TikTok" && allTikToks.length > 0 && (
                    <span
                      className="ml-1.5 font-mono text-[7px] px-1 py-0.5 border"
                      style={{
                        color: "oklch(0.58 0.2 300)",
                        borderColor: "oklch(0.58 0.2 300 / 0.4)",
                      }}
                    >
                      {allTikToks.length}
                    </span>
                  )}
                </button>
              ),
            )}
          </div>

          <div className="p-4">
            {galleryFormat === "TikTok" ? (
              allTikToks.length === 0 ? (
                <div className="py-8 text-center font-mono text-[9px] text-[oklch(0.25_0.02_280)] tracking-wider">
                  No TikTok pieces generated yet — generate films to
                  auto-produce short content
                </div>
              ) : (
                <div className="space-y-3">
                  <div className="flex items-center justify-between mb-2">
                    <div className="font-mono text-[8px] tracking-widest text-[oklch(0.35_0.03_280)]">
                      {allTikToks.length} SEALED PIECE
                      {allTikToks.length !== 1 ? "S" : ""}
                    </div>
                    {films.length > 0 && (
                      <button
                        type="button"
                        onClick={() =>
                          generateTikTok({
                            title: films[0].title,
                            archType: films[0].archType,
                            genre: "Film",
                          })
                        }
                        className="font-mono text-[7px] tracking-widest border border-[oklch(0.58_0.2_300_/_0.4)] text-[oklch(0.58_0.2_300)] px-2 py-1 hover:bg-[oklch(0.58_0.2_300_/_0.06)] transition-colors"
                        data-ocid="social.gallery.generate_tiktok"
                      >
                        + GENERATE NEW
                      </button>
                    )}
                  </div>
                  <div className="flex gap-3 overflow-x-auto scrollbar-thin pb-3">
                    {allTikToks.map((piece) => (
                      <div
                        key={piece.id}
                        className="flex-shrink-0 flex flex-col items-center gap-1.5"
                      >
                        {/* Full 9:16 inline TikTok card */}
                        <div
                          className="relative overflow-hidden border border-[oklch(0.20_0.02_280)] hover:border-[oklch(0.58_0.2_300_/_0.5)] transition-colors"
                          style={{
                            width: 108,
                            aspectRatio: "9/16",
                            background: "oklch(0.06 0.008 280)",
                          }}
                          data-ocid={`social.tiktok.preview.${piece.id}`}
                        >
                          <TikTokCard piece={piece} size="thumb" />
                          {/* Duration badge */}
                          <div
                            className="absolute top-1 right-1 font-mono text-[6px] px-1 py-0.5"
                            style={{
                              background: "rgba(1,2,10,0.75)",
                              color: piece.archColor,
                              border: `0.5px solid ${piece.archColor.replace(")", " / 0.4)")}`,
                            }}
                          >
                            {piece.duration}s
                          </div>
                        </div>
                        <div className="font-mono text-[6px] text-[oklch(0.30_0.02_280)] text-center max-w-[108px] truncate">
                          {piece.filmTitle.slice(0, 16)}
                        </div>
                        <div className="flex items-center gap-1">
                          {piece.sealStatus === "SEALED" && (
                            <span className="font-mono text-[5px] text-[oklch(0.68_0.19_132)]">
                              ⬡ SEALED
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )
            ) : (
              <div className="py-8 text-center">
                <div className="font-mono text-[9px] text-[oklch(0.25_0.02_280)] tracking-wider mb-2">
                  {galleryFormat} assets auto-generate when social plans are
                  created
                </div>
                <div className="font-mono text-[8px] text-[oklch(0.20_0.02_280)]">
                  Auto-generate plans above to populate this gallery
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
